### ISSUE TITLE
Could not retrieve data

### ISSUE THREAD

**Issue by Bpnwh** [Uwe1958/ioBroker.bluesound#10]
Hallo
Ich verwende deinen Adapter für einen Node. Soweit funktioniert er. allerdings bekomme ich immer diese Fehler.
`Could not retrieve data: TypeError: Cannot read properties of null (reading '1')`

Ich wollte auch Fragen, ob du den Adapter weiter entwickeln würdest bzw. tust. Habe dazu was im Iobroker Forum geschrieben.

https://forum.iobroker.net/topic/51705/test-adapter-bluesound-v-0-0-x-github?_=1675751751365

**Comment by Uwe1958** [comment]
Hallo

Danke für Deine Nachfrage bzw. Meldung.

Welche Version hast Du installiert? Die neueste Corrected Version 0.1.5 sollte das eigentlich behoben haben!?

Wenn das tatsächlich mit dieser Version auftritt, könntest Du mir die Ausgabe schicken, die Du erhältst, wenn Du http://[Player IP]:11000/Status eingibst.

Irgendetwas in Deiner Ausgabe wäre dann wohl anders.

Natürlich könnten wir gemeinsam überlegen, was im Adapter noch zu realisieren wäre.

**Comment by Bpnwh** [comment]
Hallo
Habe jetzt die Version 0.1.5. installiert. Scheint so als das Problem nicht mehr auftritt. 

Ja das wäre toll wenn wir hier weiter machen könnte. 
Dachte das man hier die Funktionen des Heos Adapter nachbauen könnte. 
Denn habe ich am laufen, ist ja eigentlich das gleiche wie Bluesound nur von Denon.

**Comment by Uwe1958** [comment]
Schön, dass das Problem wohl gelöst ist.

Ich müsste mir den Heos Adapter mal anschauen. Was würde Dir an dem bluesound Adapter noch fehlen?

**Comment by Bpnwh** [comment]
Schön wäre wenn man könnte:

- Titel sehen
- Cover angezeigt wird
- Nächster Titel; Voriger Titel
- event. zB auf Favoriten von Amazon Musik usw. zugreifen könnte.


Hast du ein Heos System? Sonst könnte ich die es mal zeigen.?

**Comment by Uwe1958** [comment]
Zu Deinen Kommentaren:

Der aktuelle Titel wird in bluesound.x.info.title1 bis ...title3 bereitgestellt.

Ein Cover bzw. ein evtl. vorhandenes Logo (beim Streamen) wird in bluesound.x.info.image bereitgestellt.

Die nächsten Titel etc. muss ich noch prüfen, wie die vom Player bereitgestellt werden.

Auf Amazon Musik greife ich nicht zu, hier weiss ich auch nicht, wie diesbezügliche Informationen vom Player gesendet werden. Vielleich könntest Du mir tatsächlich mal das Ergebnis von http://[Player IP]:11000/Status schicken, während von Amazon Musik gestreamt wird. Daraus kann ich dann vielleicht ableiten, welche Infos noch zur Verfüügung gestellt werden könnten.

**Comment by Uwe1958** [comment]
Vielen Dank für den Ausdruck und die Fragen zur Klarstellung.

Ich sehe, dass nun zusätzliche tags (<album>, <artist> und <name>) ausgegeben werden.

Diese decken sich jedoch mit den Informationen in <title1> bis <title3>. Insofern sehe ich nicht, dass da zusätzliche Infos daherkommen. Es wäre aber mit relativ wenig Aufwand möglich, hier zusätzliche Objekte anzulegen und die Informationen dort reinzuschreiben.

Zu Deinen Fragen zur Bedienung:

Ich setze im Vis einfach nur den entsprechenden Wert (z.B. Stop) auf True. Dem Adapter ist es egal, ob da vorher schon True drinstand. Du musst also die Werte nicht zurücksetzen. Im .state Objekt ist dann der aktuelle Zustand eingetragen.

**Comment by Bpnwh** [comment]
Wenn du eben Zeit hast dafür, dann würde ich mich freuen wenn du zusätzliche Objekte anlegst. Sprich alles was möglich ist. Vielleicht kann es auch wer anderes benötigen.  Finde ich super das es den Adapter gibt.  Eventuell kann man den auch dann offiziell bei den Adaptern sehen.

**Comment by Uwe1958** [comment]
Ich habe mich nun mal wieder an den Adapter gemacht. Generell bleibt es bei den erzeugten Objekten. Die Tags album, artist und name habe ich nicht übernommen, da sie nicht immer übergeben werden und deshalb eine komplexe Struktur im Code notwendig gewesen wäre, die immer erst prüft, ob der Tag da ist oder nicht. Die Informationen sind ohnehin identisch mit title1 (=name), title2 (=artist) und title3 (=album), die geschrieben werden.

Zusätzlich stelle ich aber secs (aktuelle Sekunden im Lied) und totlen (Gesamtdauer des Lieds) zusätzlich auch als String im Zeitformat als strSecs bzw. strTotLen zur Verfügung. Diese kann man gut in einem entsprechenden Display anzeigen, ohne dass man im vis eine umständliche Umformatierung machen muss.

Wenn Deinerseits michts dagegen spricht würde ich den Issue damit schliessen (das ursprüngliche Thema ist ohnehin schon gelöst).

**Comment by Bpnwh** [comment]
Super Danke.
Ja den Issue kannst du schließen.

**Comment by Uwe1958** [comment]
Issue geschlossen
