### ISSUE TITLE
Volume state read

### ISSUE THREAD

**Issue by Tighubb** [Uwe1958/ioBroker.bluesound#12]
Hello. When changing the volume on the Bluesound device (in my case a Pulse Flex 2i) doesn't update the volume number in iobroker. Can it be implemented or am i doing something wrong?

**Comment by Tighubb** [comment]
Thanks for the reply. 
I'm ready to test all new implemented functions. I've already other functions in mind but let first get this one with the volume finished.

**Comment by Uwe1958** [comment]
Hello Tighubb,

there is a new version that now also reads the volume regularly (defined by the polling interval). The current volume is written into ....info.volume. The object ....control.volume is used to send volume changes to the player
