### ISSUE TITLE
Please consider adding adapter to repositories

### ISSUE THREAD

**Issue by mcm1957** [Uwe1958/ioBroker.bluesound#27]
PLease request addition to our repositories / LATEST repository if adapter is working for users.
See https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-latest-repository

Please feel free to ask if you need any help.

**Comment by Uwe1958** [comment]
There is a pull request on the adapter whit pending approval.

**Comment by Uwe1958** [comment]
Added to latest repository by [#4089](https://github.com/ioBroker/ioBroker.repositories/pull/4089) on November 24
